apiVersion: kafka.myorg.io/v1alpha1
kind: KafkaTopic
metadata:
  name: new-topic
  namespace: kafka
spec:
  topic: poc-topic-ci
  partitions: 3
  replicationFactor: 2
  acl:
    principal: "User:CN=client-app"
    operation: "Read"

