apiVersion: batch/v1
kind: CronJob
metadata:
  name: kafka-operator
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kafka-manager
            image: bitnami/kafka:3.6
            command: ["/bin/bash", "-c"]
            args:
              - |
                BOOTSTRAP="$BOOTSTRAP_SERVER"
                for row in $(jq -c '.[]' /config/topics.json); do
                  NAME=$(echo $row | jq -r '.name')
                  PART=$(echo $row | jq -r '.partitions')
                  REPL=$(echo $row | jq -r '.replicationFactor')
                  kafka-topics.sh --bootstrap-server $BOOTSTRAP --create --if-not-exists --topic $NAME --partitions $PART --replication-factor $REPL
                done
                for row in $(jq -c '.[]' /config/acls.json); do
                  kafka-acls.sh --bootstrap-server $BOOTSTRAP                     --add --allow-principal "$(echo $row | jq -r '.principal')"                     --operation "$(echo $row | jq -r '.operation')"                     --resource-type "$(echo $row | jq -r '.resourceType')"                     --resource-name "$(echo $row | jq -r '.resourceName')"
                done
            volumeMounts:
              - name: tls-certs
                mountPath: /certs
              - name: kafka-config
                mountPath: /config
          restartPolicy: OnFailure
          volumes:
          - name: tls-certs
            secret:
              secretName: msk-client-cert
          - name: kafka-config
            configMap:
              name: kafka-definitions