apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rds-job-sa
    namespace: default
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
